### ISSUE TITLE
Fails to install on Ubuntu 14.04.1

### ISSUE THREAD

**Issue by kevinquinnyo** [facebook/mcrouter#88]
```
PoolFactory.cpp: In function ‘mc_protocol_t facebook::memcache::mcrouter::{anonymous}::parseProtocol(const folly::dynamic&, mc_protocol_t)’:
PoolFactory.cpp:39:32: error: ‘asciiCaseInsensitive’ is not a member of ‘folly’
     if (equalStr("ascii", str, folly::asciiCaseInsensitive)) {
                                ^
PoolFactory.cpp:41:42: error: ‘asciiCaseInsensitive’ is not a member of ‘folly’
     } else if (equalStr("umbrella", str, folly::asciiCaseInsensitive)) {
                                          ^
mv -f .deps/libmcroutercore_a-McrouterInstance.Tpo .deps/libmcroutercore_a-McrouterInstance.Po
g++ -DHAVE_CONFIG_H   -I.. -I/root/tss/bin//pkgs/folly/folly/test/gtest-1.6.0/include -I/root/tss/bin//install/include -I/root/tss/bin//pkgs/double-conversion  -DLIBMC_FBTRACE_DISABLE  -Wno-missing-field-initializers -Wno-deprecated -O3 -g -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -std=gnu++0x -g -O2 -MT libmcroutercore_a-ProxyClientCommon.o -MD -MP -MF .deps/libmcroutercore_a-ProxyClientCommon.Tpo -c -o libmcroutercore_a-ProxyClientCommon.o `test -f 'ProxyClientCommon.cpp' || echo './'`ProxyClientCommon.cpp
make[2]: *** [libmcroutercore_a-PoolFactory.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f .deps/libmcroutercore_a-ProxyClientCommon.Tpo .deps/libmcroutercore_a-ProxyClientCommon.Po
mv -f .deps/libmcroutercore_a-McrouterClient.Tpo .deps/libmcroutercore_a-McrouterClient.Po
mv -f .deps/libmcroutercore_a-proxy.Tpo .deps/libmcroutercore_a-proxy.Po
make[2]: Leaving directory `/root/tss/bin/mcrouter/mcrouter'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/tss/bin/mcrouter/mcrouter'
make: *** [all] Error 2
```

I don't know if this is an issue with folly or with mcrouter, but I'm using the latest master from mcrouter which produces this error.

I ran, per instructions:
```
./install_ubuntu_14.04.sh /root/tss/bin/ -j4
```

**Comment by alikhtarov** [comment]
I believe this is due to a recent folly update that we haven't synced with (the commit that broke backwards compatibility is https://github.com/facebook/folly/commit/40673e015ab66a54ea900c89a9e367819f389d45). @pavlo-fb will be pushing the new version of mcrouter today to take care of this.

**Comment by kevinquinnyo** [comment]
Thanks @alikhtarov !

Are there any plans to create a PPA (for Debian / Ubuntu), and/or an RPM repo (for RHEL / CentOS) ?

If not, what should I do to ensure that I always pull stable code that will compile without problems like this?

**Comment by pavlo-fb** [comment]
@kevinquinnyo should be fixed now, I've just pushed v8.

Re stable versions. The code we push should be stable as long as dependencies (the main dependency is folly) didn't change.

We are looking for the best way to make mcrouter installation as simple and robust as possible. We already added docker build, which should make things a little bit better. Some other ideas:
- The simplest one: hard code version/commit of every dependency in our build scripts.
- PPAs and RPMs sound like another option.
- Also we may one day publish prebuilt packages.

Any feedback here is highly appreciated, since we don't really know what are the use cases and what people actually want.

**Comment by kevinquinnyo** [comment]
@pavlo-fb thanks for the quick patch.

:+1: for prebuilt packages!

**Comment by bmorton** [comment]
We use mcrouter at Yammer and we build a package for Ubuntu 12.04 every time a new version comes out.  The build itself is a bit of a scramble to make sure all the dependencies line up properly and I think we're still having some issues running the tests under 12.04.  We would be really really happy with a prebuilt 12.04 package!

**Comment by bmorton** [comment]
@pavlo-fb will a release get cut for the newest version at some point?

**Comment by bmorton** [comment]
Nevermind, I see the 0.8.0 release listed now!  Either it was hiding from me last night or I just missed it somehow.  Thanks!

**Comment by kevinquinnyo** [comment]
@bmorton I'd be interested to see the ubuntu 12.04 package you have and how you're building them if it's not too much trouble of course.  I would love to build one for 14.04 but I haven't gotten around to it -- also it's been a while since I've done any debian packaging

**Comment by bmorton** [comment]
Like I mentioned, it's a bit of a scramble currently, but we're close to having it automated. Gimme a few days to get it wrapped up and get approval to release and I'm happy to share it.

**Comment by kevinquinnyo** [comment]
Broken again.  So I'm actually installing mcrouter via configuration management as part of production deployments and this is starting to cause me a lot of headache as folly becomes incompatible with mcrouter every couple of weeks.  Does anyone have any suggestions?  Should I just stick with a known-working release tag for folly + mcrouter for now?

**Comment by alikhtarov** [comment]
@kevinquinnyo Thanks for the report, yeah for now just using a known working tag for folly + mcrouter is a best approach. I'm also pushing a new version of mcrouter today which should work against the latest folly. Unfortunately folly compatibility is a huge problem for all of our open source repos, and it's something we're working to resolve in the next couple of months.
We're also figuring out how to ship pre-built packages as @pavlo-fb mentioned (looks like there are no legal roadblocks anymore and we can just do it :))

**Comment by alikhtarov** [comment]
@kevinquinnyo The error you saw with folly had nothing to do with mcrouter, folly build itself was broken. Should be fixed with this commit: https://github.com/facebook/folly/commit/68b39c3094ded827c970b12019ceebac5f425eaa - please try again.

**Comment by bmorton** [comment]
@kevinquinnyo, finally happy to report back that we've got this working and approved to share :D

We use this Dockerfile to build a package for running mcrouter 0.9 in our production environment on Ubuntu 12.04: https://github.com/yammer/mcrouter-build-docker

**Comment by kevinquinnyo** [comment]
@bmorton Awesome!  I'll test it this evening.  Thanks a lot, this actually saves us a lot of time on deployment.

**Comment by jmswen** [comment]
@kevinquinnyo Have you had any issues with mcrouter builds recently?  On this note, we are now cutting a biweekly release branch, which we hope will be more resilient to third-party incompatibilities than our master branch (which we are now pushing to continuously).  Our first stable release branch is the `release-14-0` branch.

**Comment by kevinquinnyo** [comment]
@jmswen I haven't noticed any build issues lately, although i wasn't building nightly or testing every release lately.  That's great to hear though because @bmorton and I have been building ubuntu .deb packages and it would be nice to know which releases should be considered more stable for automated package building.
